---
creation_rules:
  - path_regex: .*\.sops\.json
    key_groups:
      - age:
          - age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
  - path_regex: .*\.sops\.toml
    key_groups:
      - age:
          - age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
  - path_regex: .*\.sops\.env
    key_groups:
      - age:
          - age1ayu5h4m5gqfchewyk6vqm2ts95n3q947lldcwf4cjclqx0kec5fq5dha7q
