; Make sure to update the epoch time in the SOA records so coreDNS picks up the changes automatically
; https://www.epochconverter.com/

; SOA Records
$TTL 3600
$ORIGIN ctec.run.
@ 3600 IN SOA gateway.ctec.run. gateway.ctec.run. (
  1682790096         ; serial number (epoch timestamp)
  7200               ; refresh period
  3600               ; retry period
  1209600            ; expire time
  3600               ; minimum ttl
)

; NS Records
@                          IN  NS gateway.ctec.run.

; LAN
gateway                    IN  A  10.0.0.1

; Trusted
shinobu                    IN  A 10.0.1.5
yuzu                       IN  A 10.0.1.50

; Servers
shana                      IN  A  10.0.2.4
uiharu                     IN  A  10.0.2.10
anya                       IN  A  10.0.2.11
sakura                     IN  A  10.0.2.12
rem                        IN  A  10.0.2.13
ram                        IN  A  10.0.2.14

; IOT

; Video

; LXD
builder                    IN  A  10.0.2.95
minio                      IN  A  10.0.2.97
postgres                   IN  A  10.0.2.94
talos                      IN  A  10.0.2.93

; Containers
cluster                    IN  A  10.5.0.2
unifi                      IN  A  10.5.0.10

; CNAME records
nas                        IN  CNAME  shana.ctec.run.
s3                         IN  CNAME  minio.ctec.run.