global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leresolver

certificatesResolvers:
  leresolver:
    acme:
      email: cbc02009@kokoro.wtf
      storage: /data/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers: ["1.1.1.1:53", "8.8.8.8:53"]

serversTransport:
  insecureSkipVerify: true

http:
  routers:
    dashboard:
      rule: Host(`traefik.kokoro.wtf`)
      service: api@internal
    unifi:
      rule: Host(`unifi.kokoro.wtf`)
      entryPoints: ["websecure"]
      service: unifi
    himari:
      rule: Host(`himari.kokoro.wtf`)
      entryPoints: ["websecure"]
      service: himari
    kiki:
      rule: Host(`kiki.kokoro.wtf`)
      entryPoints: ["websecure"]
      service: kiki
    # minio:
    #   rule: Host(`minio.kokoro.wtf`)
    #   service: minio_ui
    #   entryPoints: ["websecure"]
  services:
    himari:
      loadBalancer:
        servers:
          - url: http://himari.ctec.run
      # minio_ui:
      #   loadBalancer:
      #     servers:
      #       - url: http://minio.ctec.run:9000
    unifi:
      loadBalancer:
        servers:
          - url: https://10.5.0.10:8443
    kiki:
      loadBalancer:
        servers:
          - url: https://kiki.ctec.run:8080